export const GET_ALL_VIDEOGAMES = 'GET_ALL_VIDEOGAMES'; 
export const GET_VIDEOGAMES_BY_ORIGIN = 'GET_VIDEOGAMES_BY_ORIGIN'; 
export const GET_VIDEOGAMES_BY_NAME = 'GET_VIDEOGAMES_BY_NAME'; 
export const GET_VIDEOGAME_BY_ID = 'GET_VIDEOGAME_BY_ID';
export const GET_GENRES = 'GET_GENRES';
export const ORDER_ALPHABETICALLY = 'ORDER_ALPHABETICALLY'; 
export const FILTER_BY_GENRES = 'FILTER_BY_GENRES';
export const ORDER_BY_RAITING = 'ORDER_BY_RAITING'; 
export const CREATED_GAMES = 'CREATED_GAMES'; 
export const CREATE_GAME = 'CREATE_GAME';
export const MODIFY_GAME = 'MODIFY_GAME'; 
export const DELETED_GAME = 'DELETED_GAME';
export const DELETE_STATES = 'DELETE_STATES'



